import * as React from 'react'
import { createContext, useContext, useState, useEffect } from 'react'
import { Language } from '../types'
import { siteSettings } from '../config'

interface LanguageContextType {
  currentLanguage: string
  setLanguage: (language: string) => void
  languages: Language[]
  t: (key: string, params?: Record<string, string>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Simple translation system
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.worldcup2026': 'World Cup 2026',
    'nav.cart': 'Cart',
    'nav.login': 'Sign In',
    'nav.register': 'Sign Up',
    'nav.profile': 'Profile',
    'nav.orders': 'Orders',
    'nav.logout': 'Sign Out',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.clear': 'Clear',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Products
    'products.title': 'Products',
    'products.featured': 'Featured Products',
    'products.new': 'New Products',
    'products.sale': 'Sale',
    'products.outOfStock': 'Out of Stock',
    'products.addToCart': 'Add to Cart',
    'products.viewDetails': 'View Details',
    'products.price': 'Price',
    'products.quantity': 'Quantity',
    'products.inStock': 'In Stock',
    'products.origin': 'Origin',
    'products.brand': 'Brand',
    'products.description': 'Description',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.item': 'item',
    'cart.items': 'items',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.removeItem': 'Remove Item',
    'cart.updateQuantity': 'Update Quantity',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shippingInfo': 'Shipping Information',
    'checkout.paymentInfo': 'Payment Information',
    'checkout.orderSummary': 'Order Summary',
    'checkout.placeOrder': 'Place Order',
    'checkout.billingSameAsShipping': 'Billing address same as shipping',
    'checkout.billingInfo': 'Billing Information',
    
    // Auth
    'auth.login': 'Sign In',
    'auth.register': 'Sign Up',
    'auth.logout': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember Me',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signInWith': 'Sign in with',
    'auth.signUpWith': 'Sign up with',
    
    // Profile
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.addressInfo': 'Address Information',
    'profile.orderHistory': 'Order History',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    
    // Orders
    'orders.title': 'Orders',
    'orders.noOrders': 'No orders found',
    'orders.orderNumber': 'Order Number',
    'orders.orderDate': 'Order Date',
    'orders.orderStatus': 'Status',
    'orders.orderTotal': 'Total',
    'orders.viewOrder': 'View Order',
    'orders.tracking': 'Tracking',
    
    // World Cup 2026
    'worldcup.title': 'World Cup 2026',
    'worldcup.comingSoon': 'Coming Soon',
    'worldcup.description': 'Get ready for the biggest football event!',
    'worldcup.features': 'Features',
    'worldcup.predictions': 'Match Predictions',
    'worldcup.countries': 'Country Collections',
    'worldcup.achievements': 'Achievements & Badges',
    'worldcup.stories': 'Cultural Stories',
    'worldcup.stats': 'Live Statistics',
    
    // Homepage
    'homepage.hero.subtitle': 'Discover amazing candies from around the world. Premium quality, authentic flavors, and worldwide shipping.',
    'homepage.hero.shopNow': 'Shop Now',
    'homepage.stats.featuredTitle': 'FEATURED SWEET TREATS',
    'homepage.stats.featuredDesc': 'Hand-picked by our global candy experts, these treats represent the',
    'homepage.stats.bestFlavors': 'best flavors',
    'homepage.stats.fromWorld': 'from around the world.',
    'homepage.stats.countries': 'Countries',
    'homepage.stats.products': 'Products',
    'homepage.stats.freshStock': 'Fresh Stock',
    'homepage.stats.rating': 'Rating',
    'homepage.features.title': 'Why Choose SweetTrip?',
    'homepage.features.whyChoose': 'Why Choose Sweet Trip?',
    'homepage.features.subtitle': 'We bring you the best of international candy culture with unmatched quality and service.',
    'homepage.features.fastShipping': 'Fast & Free Shipping',
    'homepage.features.fastShippingDesc': 'Free shipping on orders over $60. Get your international candy favorites delivered quickly and safely to your door.',
    'homepage.features.authentic': '100% Authentic',
    'homepage.features.authenticDesc': 'All our products are sourced directly from manufacturers and verified distributors. No imitations, just authentic flavors.',
    'homepage.features.curated': 'Curated Selection',
    'homepage.features.curatedDesc': 'Our team personally tastes and selects every product. We only offer candies that meet our high standards for quality and taste.',
    'homepage.stats.title': 'SweetTrip by the Numbers',
    'homepage.cta.title': 'Ready to Start Your Sweet Journey?',
    'homepage.cta.subtitle': 'Join thousands of satisfied customers and discover your new favorite treats.',
    'homepage.featuredProducts': 'Featured Products',
    'homepage.featuredProductsDesc': 'Discover our handpicked selection of premium international candies',
    'homepage.featured': 'Featured',
    'homepage.outOfStock': 'Out of Stock',
    'homepage.addToCart': 'Add to Cart',
    'homepage.viewAll': 'View All Products',
    'homepage.worldcup.title': 'FIFA World Cup 2026',
    'homepage.worldcup.desc': 'Get ready for the biggest football event! Special collections, predictions, and exclusive merchandise coming soon.',
    'homepage.worldcup.explore': 'Explore World Cup 2026',
    'homepage.newsletter.title': 'Stay Sweet!',
    'homepage.newsletter.desc': 'Get the latest updates on new products and exclusive offers.',
    'homepage.newsletter.placeholder': 'Enter your email',
    'homepage.newsletter.subscribe': 'Subscribe',
    'homepage.soldBadge': 'Over {{count}} Sold',
    
    // Footer
    'footer.description': 'Discover amazing candies from around the world. Premium quality, authentic flavors, and worldwide shipping.',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.products': 'Products',
    'footer.allProducts': 'All Products',
    'footer.featured': 'Featured',
    'footer.newArrivals': 'New Arrivals',
    'footer.worldCup': 'World Cup 2026',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.shippingInfo': 'Shipping Info',
    'footer.returns': 'Returns',
    'footer.sizeGuide': 'Size Guide',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.refund': 'Refund Policy',
    'footer.newsletter': 'Stay Sweet!',
    'footer.newsletterDesc': 'Get the latest updates on new products and exclusive offers.',
    'footer.subscribe': 'Subscribe',
    'footer.followUs': 'Follow Us',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.enterEmail': 'Enter your email',
    
    // Header
    'header.searchPlaceholder': 'Search Product Name / Type or Brand',
    'header.searchButton': 'Search',
    'header.freeShipping': 'FREE SHIPPING on orders over $60',
    'header.categories': 'Categories',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.products': 'Productos',
    'nav.worldcup2026': 'Mundial 2026',
    'nav.cart': 'Carrito',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.profile': 'Perfil',
    'nav.orders': 'Pedidos',
    'nav.logout': 'Cerrar Sesión',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.remove': 'Quitar',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.clear': 'Limpiar',
    'common.submit': 'Enviar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.open': 'Abrir',
    'common.yes': 'Sí',
    'common.no': 'No',
    
    // Products
    'products.title': 'Productos',
    'products.featured': 'Productos Destacados',
    'products.new': 'Productos Nuevos',
    'products.sale': 'Oferta',
    'products.outOfStock': 'Agotado',
    'products.addToCart': 'Agregar al Carrito',
    'products.viewDetails': 'Ver Detalles',
    'products.price': 'Precio',
    'products.quantity': 'Cantidad',
    'products.inStock': 'En Stock',
    'products.origin': 'Origen',
    'products.brand': 'Marca',
    'products.description': 'Descripción',
    
    // Cart
    'cart.title': 'Carrito de Compras',
    'cart.empty': 'Tu carrito está vacío',
    'cart.item': 'artículo',
    'cart.items': 'artículos',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Envío',
    'cart.tax': 'Impuestos',
    'cart.total': 'Total',
    'cart.checkout': 'Finalizar Compra',
    'cart.continueShopping': 'Seguir Comprando',
    'cart.removeItem': 'Eliminar Artículo',
    'cart.updateQuantity': 'Actualizar Cantidad',
    
    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.shippingInfo': 'Información de Envío',
    'checkout.paymentInfo': 'Información de Pago',
    'checkout.orderSummary': 'Resumen del Pedido',
    'checkout.placeOrder': 'Realizar Pedido',
    'checkout.billingSameAsShipping': 'Dirección de facturación igual a la de envío',
    'checkout.billingInfo': 'Información de Facturación',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.logout': 'Cerrar Sesión',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.phone': 'Teléfono',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.rememberMe': 'Recordarme',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.dontHaveAccount': '¿No tienes una cuenta?',
    'auth.signInWith': 'Iniciar sesión con',
    'auth.signUpWith': 'Registrarse con',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Información Personal',
    'profile.addressInfo': 'Información de Dirección',
    'profile.orderHistory': 'Historial de Pedidos',
    'profile.editProfile': 'Editar Perfil',
    'profile.saveChanges': 'Guardar Cambios',
    
    // Orders
    'orders.title': 'Pedidos',
    'orders.noOrders': 'No se encontraron pedidos',
    'orders.orderNumber': 'Número de Pedido',
    'orders.orderDate': 'Fecha del Pedido',
    'orders.orderStatus': 'Estado',
    'orders.orderTotal': 'Total',
    'orders.viewOrder': 'Ver Pedido',
    'orders.tracking': 'Seguimiento',
    
    // World Cup 2026
    'worldcup.title': 'Mundial 2026',
    'worldcup.comingSoon': 'Próximamente',
    'worldcup.description': '¡Prepárate para el evento de fútbol más grande!',
    'worldcup.features': 'Características',
    'worldcup.predictions': 'Predicciones de Partidos',
    'worldcup.countries': 'Colecciones por País',
    'worldcup.achievements': 'Logros y Medallas',
    'worldcup.stories': 'Historias Culturales',
    'worldcup.stats': 'Estadísticas en Vivo',
    
    // Homepage
    'homepage.hero.subtitle': 'Descubre dulces increíbles de todo el mundo. Calidad premium, sabores auténticos y envío mundial.',
    'homepage.hero.shopNow': 'Comprar Ahora',
    'homepage.stats.featuredTitle': 'DULCES DESTACADOS',
    'homepage.stats.featuredDesc': 'Seleccionados por nuestros expertos en dulces internacionales, estos productos representan los',
    'homepage.stats.bestFlavors': 'mejores sabores',
    'homepage.stats.fromWorld': 'de todo el mundo.',
    'homepage.stats.countries': 'Países',
    'homepage.stats.products': 'Productos',
    'homepage.stats.freshStock': 'Stock Fresco',
    'homepage.stats.rating': 'Calificación',
    'homepage.features.title': '¿Por qué elegir SweetTrip?',
    'homepage.features.whyChoose': '¿Por qué elegir Sweet Trip?',
    'homepage.features.subtitle': 'Te traemos lo mejor de la cultura dulce internacional con calidad y servicio inigualables.',
    'homepage.features.fastShipping': 'Envío Rápido y Gratis',
    'homepage.features.fastShippingDesc': 'Envío gratis en pedidos superiores a $60. Recibe tus dulces internacionales favoritos de forma rápida y segura en tu puerta.',
    'homepage.features.authentic': '100% Auténtico',
    'homepage.features.authenticDesc': 'Todos nuestros productos provienen directamente de fabricantes y distribuidores verificados. Sin imitaciones, solo sabores auténticos.',
    'homepage.features.curated': 'Selección Curada',
    'homepage.features.curatedDesc': 'Nuestro equipo prueba y selecciona personalmente cada producto. Solo ofrecemos dulces que cumplen con nuestros altos estándares de calidad y sabor.',
    'homepage.stats.title': 'SweetTrip en números',
    'homepage.cta.title': '¿Listo para comenzar tu viaje dulce?',
    'homepage.cta.subtitle': 'Únete a miles de clientes satisfechos y descubre tus nuevos dulces favoritos.',
    'homepage.featuredProducts': 'Productos Destacados',
    'homepage.featuredProductsDesc': 'Descubre nuestra selección de dulces internacionales premium',
    'homepage.featured': 'Destacado',
    'homepage.outOfStock': 'Agotado',
    'homepage.addToCart': 'Agregar al Carrito',
    'homepage.viewAll': 'Ver Todos los Productos',
    'homepage.worldcup.title': 'Copa Mundial FIFA 2026',
    'homepage.worldcup.desc': '¡Prepárate para el evento de fútbol más grande! Colecciones especiales, predicciones y mercancía exclusiva próximamente.',
    'homepage.worldcup.explore': 'Explorar Mundial 2026',
    'homepage.newsletter.title': '¡Mantente Dulce!',
    'homepage.newsletter.desc': 'Recibe las últimas actualizaciones sobre nuevos productos y ofertas exclusivas.',
    'homepage.newsletter.placeholder': 'Ingresa tu correo',
    'homepage.newsletter.subscribe': 'Suscribirse',
    'homepage.soldBadge': 'Más de {{count}} Vendidos',
    
    // Footer
    'footer.description': 'Descubre dulces increíbles de todo el mundo. Calidad premium, sabores auténticos y envío mundial.',
    'footer.company': 'Empresa',
    'footer.aboutUs': 'Sobre Nosotros',
    'footer.contact': 'Contacto',
    'footer.careers': 'Carreras',
    'footer.press': 'Prensa',
    'footer.products': 'Productos',
    'footer.allProducts': 'Todos los Productos',
    'footer.featured': 'Destacados',
    'footer.newArrivals': 'Nuevos',
    'footer.worldCup': 'Mundial 2026',
    'footer.support': 'Soporte',
    'footer.helpCenter': 'Centro de Ayuda',
    'footer.shippingInfo': 'Info de Envío',
    'footer.returns': 'Devoluciones',
    'footer.sizeGuide': 'Guía de Tallas',
    'footer.legal': 'Legal',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cookies': 'Política de Cookies',
    'footer.refund': 'Política de Reembolso',
    'footer.newsletter': '¡Mantente Dulce!',
    'footer.newsletterDesc': 'Recibe las últimas actualizaciones sobre nuevos productos y ofertas exclusivas.',
    'footer.subscribe': 'Suscribirse',
    'footer.followUs': 'Síguenos',
    'footer.allRightsReserved': 'Todos los derechos reservados.',
    'footer.enterEmail': 'Ingresa tu correo',
    
    // Header
    'header.searchPlaceholder': 'Buscar Producto / Tipo o Marca',
    'header.searchButton': 'Buscar',
    'header.freeShipping': 'ENVÍO GRATIS en pedidos superiores a $60',
    'header.categories': 'Categorías',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.worldcup2026': 'Coupe du Monde 2026',
    'nav.cart': 'Panier',
    'nav.login': 'Se connecter',
    'nav.register': "S'inscrire",
    'nav.profile': 'Profil',
    'nav.orders': 'Commandes',
    'nav.logout': 'Déconnexion',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.remove': 'Retirer',
    'common.view': 'Voir',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.clear': 'Effacer',
    'common.submit': 'Soumettre',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.close': 'Fermer',
    'common.open': 'Ouvrir',
    'common.yes': 'Oui',
    'common.no': 'Non',
    
    // Products
    'products.title': 'Produits',
    'products.featured': 'Produits en vedette',
    'products.new': 'Nouveaux produits',
    'products.sale': 'Promotion',
    'products.outOfStock': 'Épuisé',
    'products.addToCart': 'Ajouter au panier',
    'products.viewDetails': 'Voir les détails',
    'products.price': 'Prix',
    'products.quantity': 'Quantité',
    'products.inStock': 'En stock',
    'products.origin': 'Origine',
    'products.brand': 'Marque',
    'products.description': 'Description',
    
    // Cart
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.item': 'article',
    'cart.items': 'articles',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Livraison',
    'cart.tax': 'Taxes',
    'cart.total': 'Total',
    'cart.checkout': 'Commander',
    'cart.continueShopping': 'Continuer les achats',
    'cart.removeItem': "Retirer l'article",
    'cart.updateQuantity': 'Mettre à jour la quantité',
    
    // Checkout
    'checkout.title': 'Commander',
    'checkout.shippingInfo': 'Informations de livraison',
    'checkout.paymentInfo': 'Informations de paiement',
    'checkout.orderSummary': 'Résumé de la commande',
    'checkout.placeOrder': 'Passer la commande',
    'checkout.billingSameAsShipping': 'Adresse de facturation identique à celle de livraison',
    'checkout.billingInfo': 'Informations de facturation',
    
    // Auth
    'auth.login': 'Se connecter',
    'auth.register': "S'inscrire",
    'auth.logout': 'Déconnexion',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.phone': 'Téléphone',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.rememberMe': 'Se souvenir de moi',
    'auth.alreadyHaveAccount': 'Vous avez déjà un compte?',
    'auth.dontHaveAccount': "Vous n'avez pas de compte?",
    'auth.signInWith': 'Se connecter avec',
    'auth.signUpWith': "S'inscrire avec",
    
    // Profile
    'profile.title': 'Profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.addressInfo': 'Informations d\'adresse',
    'profile.orderHistory': 'Historique des commandes',
    'profile.editProfile': 'Modifier le profil',
    'profile.saveChanges': 'Enregistrer les modifications',
    
    // Orders
    'orders.title': 'Commandes',
    'orders.noOrders': 'Aucune commande trouvée',
    'orders.orderNumber': 'Numéro de commande',
    'orders.orderDate': 'Date de commande',
    'orders.orderStatus': 'Statut',
    'orders.orderTotal': 'Total',
    'orders.viewOrder': 'Voir la commande',
    'orders.tracking': 'Suivi',
    
    // World Cup 2026
    'worldcup.title': 'Coupe du Monde 2026',
    'worldcup.comingSoon': 'Bientôt disponible',
    'worldcup.description': 'Préparez-vous pour le plus grand événement de football!',
    'worldcup.features': 'Fonctionnalités',
    'worldcup.predictions': 'Prédictions de matchs',
    'worldcup.countries': 'Collections par pays',
    'worldcup.achievements': 'Réalisations et badges',
    'worldcup.stories': 'Histoires culturelles',
    'worldcup.stats': 'Statistiques en direct',
    
    // Homepage
    'homepage.hero.subtitle': 'Découvrez des bonbons incroyables du monde entier. Qualité premium, saveurs authentiques et livraison mondiale.',
    'homepage.hero.shopNow': 'Acheter maintenant',
    'homepage.stats.featuredTitle': 'FRIANDISES VEDETTES',
    'homepage.stats.featuredDesc': 'Sélectionnés par nos experts en bonbons internationaux, ces produits représentent les',
    'homepage.stats.bestFlavors': 'meilleures saveurs',
    'homepage.stats.fromWorld': 'du monde entier.',
    'homepage.stats.countries': 'Pays',
    'homepage.stats.products': 'Produits',
    'homepage.stats.freshStock': 'Stock Frais',
    'homepage.stats.rating': 'Note',
    'homepage.features.title': 'Pourquoi choisir SweetTrip?',
    'homepage.features.whyChoose': 'Pourquoi choisir Sweet Trip?',
    'homepage.features.subtitle': 'Nous vous apportons le meilleur de la culture sucrée internationale avec une qualité et un service inégalés.',
    'homepage.features.fastShipping': 'Livraison Rapide et Gratuite',
    'homepage.features.fastShippingDesc': 'Livraison gratuite pour les commandes de plus de 60$. Recevez vos bonbons internationaux préférés rapidement et en toute sécurité.',
    'homepage.features.authentic': '100% Authentique',
    'homepage.features.authenticDesc': 'Tous nos produits proviennent directement des fabricants et distributeurs vérifiés. Pas d\'imitations, seulement des saveurs authentiques.',
    'homepage.features.curated': 'Sélection Soignée',
    'homepage.features.curatedDesc': 'Notre équipe goûte et sélectionne personnellement chaque produit. Nous n\'offrons que des bonbons qui répondent à nos normes élevées de qualité et de goût.',
    'homepage.stats.title': 'SweetTrip en chiffres',
    'homepage.cta.title': 'Prêt à commencer votre voyage sucré?',
    'homepage.cta.subtitle': 'Rejoignez des milliers de clients satisfaits et découvrez vos nouvelles friandises préférées.',
    'homepage.featuredProducts': 'Produits en vedette',
    'homepage.featuredProductsDesc': 'Découvrez notre sélection de bonbons internationaux premium',
    'homepage.featured': 'Vedette',
    'homepage.outOfStock': 'Épuisé',
    'homepage.addToCart': 'Ajouter au panier',
    'homepage.viewAll': 'Voir tous les produits',
    'homepage.worldcup.title': 'Coupe du Monde FIFA 2026',
    'homepage.worldcup.desc': 'Préparez-vous pour le plus grand événement de football! Collections spéciales, prédictions et marchandises exclusives à venir.',
    'homepage.worldcup.explore': 'Explorer la Coupe du Monde 2026',
    'homepage.newsletter.title': 'Restez Gourmand!',
    'homepage.newsletter.desc': 'Recevez les dernières mises à jour sur les nouveaux produits et les offres exclusives.',
    'homepage.newsletter.placeholder': 'Entrez votre email',
    'homepage.newsletter.subscribe': 'S\'abonner',
    'homepage.soldBadge': 'Plus de {{count}} vendus',
    
    // Footer
    'footer.description': 'Découvrez des bonbons incroyables du monde entier. Qualité premium, saveurs authentiques et livraison mondiale.',
    'footer.company': 'Entreprise',
    'footer.aboutUs': 'À propos',
    'footer.contact': 'Contact',
    'footer.careers': 'Carrières',
    'footer.press': 'Presse',
    'footer.products': 'Produits',
    'footer.allProducts': 'Tous les produits',
    'footer.featured': 'En vedette',
    'footer.newArrivals': 'Nouveautés',
    'footer.worldCup': 'Coupe du Monde 2026',
    'footer.support': 'Support',
    'footer.helpCenter': 'Centre d\'aide',
    'footer.shippingInfo': 'Info livraison',
    'footer.returns': 'Retours',
    'footer.sizeGuide': 'Guide des tailles',
    'footer.legal': 'Légal',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.cookies': 'Politique des cookies',
    'footer.refund': 'Politique de remboursement',
    'footer.newsletter': 'Restez Gourmand!',
    'footer.newsletterDesc': 'Recevez les dernières mises à jour sur les nouveaux produits et les offres exclusives.',
    'footer.subscribe': "S'abonner",
    'footer.followUs': 'Suivez-nous',
    'footer.allRightsReserved': 'Tous droits réservés.',
    'footer.enterEmail': 'Entrez votre email',
    
    // Header
    'header.searchPlaceholder': 'Rechercher produit / type ou marque',
    'header.searchButton': 'Rechercher',
    'header.freeShipping': 'LIVRAISON GRATUITE pour les commandes de plus de 60$',
    'header.categories': 'Catégories',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.products': 'Produtos',
    'nav.worldcup2026': 'Copa do Mundo 2026',
    'nav.cart': 'Carrinho',
    'nav.login': 'Entrar',
    'nav.register': 'Cadastrar',
    'nav.profile': 'Perfil',
    'nav.orders': 'Pedidos',
    'nav.logout': 'Sair',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.add': 'Adicionar',
    'common.remove': 'Remover',
    'common.view': 'Ver',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.clear': 'Limpar',
    'common.submit': 'Enviar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.close': 'Fechar',
    'common.open': 'Abrir',
    'common.yes': 'Sim',
    'common.no': 'Não',
    
    // Products
    'products.title': 'Produtos',
    'products.featured': 'Produtos em destaque',
    'products.new': 'Produtos novos',
    'products.sale': 'Promoção',
    'products.outOfStock': 'Esgotado',
    'products.addToCart': 'Adicionar ao carrinho',
    'products.viewDetails': 'Ver detalhes',
    'products.price': 'Preço',
    'products.quantity': 'Quantidade',
    'products.inStock': 'Em estoque',
    'products.origin': 'Origem',
    'products.brand': 'Marca',
    'products.description': 'Descrição',
    
    // Cart
    'cart.title': 'Carrinho de compras',
    'cart.empty': 'Seu carrinho está vazio',
    'cart.item': 'item',
    'cart.items': 'itens',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Frete',
    'cart.tax': 'Impostos',
    'cart.total': 'Total',
    'cart.checkout': 'Finalizar compra',
    'cart.continueShopping': 'Continuar comprando',
    'cart.removeItem': 'Remover item',
    'cart.updateQuantity': 'Atualizar quantidade',
    
    // Checkout
    'checkout.title': 'Finalizar compra',
    'checkout.shippingInfo': 'Informações de envio',
    'checkout.paymentInfo': 'Informações de pagamento',
    'checkout.orderSummary': 'Resumo do pedido',
    'checkout.placeOrder': 'Fazer pedido',
    'checkout.billingSameAsShipping': 'Endereço de cobrança igual ao de envio',
    'checkout.billingInfo': 'Informações de cobrança',
    
    // Auth
    'auth.login': 'Entrar',
    'auth.register': 'Cadastrar',
    'auth.logout': 'Sair',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar senha',
    'auth.firstName': 'Nome',
    'auth.lastName': 'Sobrenome',
    'auth.phone': 'Telefone',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.rememberMe': 'Lembrar-me',
    'auth.alreadyHaveAccount': 'Já tem uma conta?',
    'auth.dontHaveAccount': 'Não tem uma conta?',
    'auth.signInWith': 'Entrar com',
    'auth.signUpWith': 'Cadastrar com',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Informações pessoais',
    'profile.addressInfo': 'Informações de endereço',
    'profile.orderHistory': 'Histórico de pedidos',
    'profile.editProfile': 'Editar perfil',
    'profile.saveChanges': 'Salvar alterações',
    
    // Orders
    'orders.title': 'Pedidos',
    'orders.noOrders': 'Nenhum pedido encontrado',
    'orders.orderNumber': 'Número do pedido',
    'orders.orderDate': 'Data do pedido',
    'orders.orderStatus': 'Status',
    'orders.orderTotal': 'Total',
    'orders.viewOrder': 'Ver pedido',
    'orders.tracking': 'Rastreamento',
    
    // World Cup 2026
    'worldcup.title': 'Copa do Mundo 2026',
    'worldcup.comingSoon': 'Em breve',
    'worldcup.description': 'Prepare-se para o maior evento de futebol!',
    'worldcup.features': 'Recursos',
    'worldcup.predictions': 'Previsões de partidas',
    'worldcup.countries': 'Coleções por país',
    'worldcup.achievements': 'Conquistas e medalhas',
    'worldcup.stories': 'Histórias culturais',
    'worldcup.stats': 'Estatísticas ao vivo',
    
    // Homepage
    'homepage.hero.subtitle': 'Descubra doces incríveis de todo o mundo. Qualidade premium, sabores autênticos e envio mundial.',
    'homepage.hero.shopNow': 'Comprar agora',
    'homepage.stats.featuredTitle': 'DOCES DESTACADOS',
    'homepage.stats.featuredDesc': 'Selecionados por nossos especialistas em doces internacionais, estes produtos representam os',
    'homepage.stats.bestFlavors': 'melhores sabores',
    'homepage.stats.fromWorld': 'de todo o mundo.',
    'homepage.stats.countries': 'Países',
    'homepage.stats.products': 'Produtos',
    'homepage.stats.freshStock': 'Estoque Fresco',
    'homepage.stats.rating': 'Avaliação',
    'homepage.features.title': 'Por que escolher SweetTrip?',
    'homepage.features.whyChoose': 'Por que escolher Sweet Trip?',
    'homepage.features.subtitle': 'Trazemos o melhor da cultura doce internacional com qualidade e serviço incomparáveis.',
    'homepage.features.fastShipping': 'Envio Rápido e Grátis',
    'homepage.features.fastShippingDesc': 'Frete grátis em pedidos acima de $60. Receba seus doces internacionais favoritos de forma rápida e segura na sua porta.',
    'homepage.features.authentic': '100% Autêntico',
    'homepage.features.authenticDesc': 'Todos os nossos produtos vêm diretamente de fabricantes e distribuidores verificados. Sem imitações, apenas sabores autênticos.',
    'homepage.features.curated': 'Seleção Curada',
    'homepage.features.curatedDesc': 'Nossa equipe prova e seleciona pessoalmente cada produto. Oferecemos apenas doces que atendem aos nossos altos padrões de qualidade e sabor.',
    'homepage.stats.title': 'SweetTrip em números',
    'homepage.cta.title': 'Pronto para começar sua jornada doce?',
    'homepage.cta.subtitle': 'Junte-se a milhares de clientes satisfeitos e descubra seus novos doces favoritos.',
    'homepage.featuredProducts': 'Produtos em destaque',
    'homepage.featuredProductsDesc': 'Descubra nossa seleção de doces internacionais premium',
    'homepage.featured': 'Destaque',
    'homepage.outOfStock': 'Esgotado',
    'homepage.addToCart': 'Adicionar ao carrinho',
    'homepage.viewAll': 'Ver todos os produtos',
    'homepage.worldcup.title': 'Copa do Mundo FIFA 2026',
    'homepage.worldcup.desc': 'Prepare-se para o maior evento de futebol! Coleções especiais, previsões e mercadorias exclusivas em breve.',
    'homepage.worldcup.explore': 'Explorar Copa do Mundo 2026',
    'homepage.newsletter.title': 'Fique Doce!',
    'homepage.newsletter.desc': 'Receba as últimas atualizações sobre novos produtos e ofertas exclusivas.',
    'homepage.newsletter.placeholder': 'Digite seu email',
    'homepage.newsletter.subscribe': 'Inscrever-se',
    'homepage.soldBadge': 'Mais de {{count}} vendidos',
    
    // Footer
    'footer.description': 'Descubra doces incríveis de todo o mundo. Qualidade premium, sabores autênticos e envio mundial.',
    'footer.company': 'Empresa',
    'footer.aboutUs': 'Sobre nós',
    'footer.contact': 'Contato',
    'footer.careers': 'Carreiras',
    'footer.press': 'Imprensa',
    'footer.products': 'Produtos',
    'footer.allProducts': 'Todos os produtos',
    'footer.featured': 'Em destaque',
    'footer.newArrivals': 'Novidades',
    'footer.worldCup': 'Copa do Mundo 2026',
    'footer.support': 'Suporte',
    'footer.helpCenter': 'Centro de ajuda',
    'footer.shippingInfo': 'Info de envio',
    'footer.returns': 'Devoluções',
    'footer.sizeGuide': 'Guia de tamanhos',
    'footer.legal': 'Legal',
    'footer.privacy': 'Política de privacidade',
    'footer.terms': 'Termos de serviço',
    'footer.cookies': 'Política de cookies',
    'footer.refund': 'Política de reembolso',
    'footer.newsletter': 'Fique Doce!',
    'footer.newsletterDesc': 'Receba as últimas atualizações sobre novos produtos e ofertas exclusivas.',
    'footer.subscribe': 'Inscrever-se',
    'footer.followUs': 'Siga-nos',
    'footer.allRightsReserved': 'Todos os direitos reservados.',
    'footer.enterEmail': 'Digite seu email',
    
    // Header
    'header.searchPlaceholder': 'Pesquisar produto / tipo ou marca',
    'header.searchButton': 'Pesquisar',
    'header.freeShipping': 'FRETE GRÁTIS em pedidos acima de $60',
    'header.categories': 'Categorias',
  },
}

interface LanguageProviderProps {
  children: React.ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<string>(
    localStorage.getItem('sweettrip-language') || siteSettings.defaultLanguage
  )

  const languages: Language[] = siteSettings.supportedLanguages.map(lang => ({
    code: lang.code,
    name: lang.name,
    flag: lang.flag,
    is_active: true,
  }))

  const setLanguage = (language: string) => {
    setCurrentLanguage(language)
    localStorage.setItem('sweettrip-language', language)
  }

  const t = (key: string, params?: Record<string, string>): string => {
    const translation = translations[currentLanguage]?.[key] || translations.en[key] || key
    
    if (params) {
      return Object.entries(params).reduce(
        (str, [param, value]) => str.replace(`{{${param}}}`, value),
        translation
      )
    }
    
    return translation
  }

  const value: LanguageContextType = {
    currentLanguage,
    setLanguage,
    languages,
    t,
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
